base_images:
  golangci-lint:
    name: golangci-lint
    namespace: ci
    tag: v1.63.4
build_root:
  project_image:
    dockerfile_path: Dockerfile.buildroot
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  commands: HOME=/tmp golangci-lint run --timeout=20m
  container:
    from: golangci-lint
- as: mapping
  commands: HOME=/tmp ./hack/ci-mapping.sh
  container:
    from: src
- as: unit
  commands: HOME=/tmp ./hack/ci-test.sh
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ci-test-mapping
